Теперь можно копать ручками и всеми предметами(#24)
SS13-Extended/Paradise pull request #42
Opened 2022-06-28 22:16 UTC by ArtemSliK

2022-06-28 23:29 UTC, valldemar2017 commented on code/game/turfs/simulated/minerals.dm
> +		to_chat(user, "<span class='notice'>You start mining...</span>")
Думаю, требуется большей эмоций, поэтому:
Вы изо всех сил пытаетесь пробиться сквозь скалу
```suggestion
		to_chat(user, "<span class='notice'>You are struggling to break through the rock...</span>")
```

2022-06-28 23:48 UTC, SuhEugene commented
А разве всеми предметами?

2022-06-29 01:02 UTC, SuhEugene commented
После теста, получается, какие результаты...

2022-06-29 02:06 UTC, SuhEugene requested changes
Идеи - лишь предложения, но фикс неотображающегося сообщения надо-надо

2022-06-29 02:06 UTC, SuhEugene commented on code/game/turfs/simulated/minerals.dm
> +			to_chat(user, "<span class='notice'>You finish cutting into the rock.</span>")
Идея 2:
@NAKAIIIII предложил такую заменку, чтоб более красиво
```suggestion
			to_chat(user, "<span class='notice'>You finish pulling the rocks away.</span>")
```

2022-06-29 02:06 UTC, SuhEugene commented on code/game/turfs/simulated/minerals.dm
> +			SSblackbox.record_feedback("tally", "pick_used_mining", 1,)
Идея 3:
Создать новую функцию, ради того чтобы в чате отобразилось название предмета копания + чтобы предметом копалось быстрее
Также сюда включены предыдущие идейки и фикс
```suggestion
		return dig_into_with_hands(user, I)

/turf/simulated/mineral/attack_hand(mob/user as mob)
	return dig_into_with_hands(user)

/turf/simulated/mineral/proc/dig_into_with_hands(mob/user, obj/item/item = null)
	var/dig_time = item ? 200 : 300
	if(last_act + dig_time > world.time) // Prevents message spam
		return
	last_act = world.time
	to_chat(user, "<span class='notice'>You are struggling to break through  \
			the rock with [item ? item : "your hands"]...</span>")

	if(do_after(user, dig_time, target = src))
		if(ismineralturf(src)) //sanity check against turf being deleted during digspeed delay
			to_chat(user, "<span class='notice'>You finish pulling the rocks away.</span>")
			gets_drilled(user)
			SSblackbox.record_feedback("tally", "pick_used_mining", 1,)
```

2022-06-29 02:08 UTC, NAKAIIIII commented on code/game/turfs/simulated/minerals.dm
> +			to_chat(user, "<span class='notice'>You finish cutting into the rock.</span>")
ыааа пинги уже и на гитхабе приходят 🏓

2022-06-29 02:48 UTC, SuhEugene commented on code/game/turfs/simulated/minerals.dm
> +	if(do_after(user, 100, target = src))
`last_act` + 50 потому что иначе только через 100 децисекунд (10 секунд) можно будет заново копать, уменьшил до 50 децисек (5 сек)
`do_after(300)` - 300 децисекунд - увеличил до 30 секунд

2022-06-29 19:00 UTC, merged