Syndie Tools for Valldemar
SS13-Extended/Paradise pull request #48
Opened 2022-07-01 00:37 UTC by NAKAIIIII

what it says in the title 
#45

2022-07-01 02:57 UTC, NAKAIIIII commented
Попытался в компактные, механизированные инструменты

2022-07-01 04:01 UTC, NAKAIIIII commented
@valldemar2017

2022-07-01 04:11 UTC, SuhEugene commented
Один день не заходил на гитхаб - два ПРа

2022-07-01 04:11 UTC, SuhEugene commented
Надо себе автопинг в дискорде на ПРы сделать...

2022-07-01 04:20 UTC, SuhEugene commented
Вот так

2022-07-01 17:21 UTC, valldemar2017 commented
@NAKAIIIII Слушай, выглядит классно. Но правда горелка немного смущает. Можешь сделать этот бак на рукояти более четким. Или может вообще его убрать

2022-07-01 17:28 UTC, valldemar2017 requested changes
Бак на горелке немного зашакален. Мб его убрать? А так всё очень круто выглядит

2022-07-01 17:46 UTC, NAKAIIIII commented
@valldemar2017 обновил сварку, проверяй
бак сделал почетче

2022-07-02 23:49 UTC, valldemar2017 approved these changes
Круть, спасибо

2022-07-02 23:49 UTC, merged